import ProfileImages from "@/assets/images/ProfilePics";
import FlagPics from "@/assets/images/CountryFlags";

export const ProfileData = [
  {
    id: "1",
    name: "Arthur",
    profileImage: ProfileImages.Pic1,
    countryImage: FlagPics.Flag1,
    Worker_Role: "Astrologer",
  },
  {
    id: "2",
    name: "Leslie",
    profileImage: ProfileImages.Pic2,
    countryImage: FlagPics.Flag2,
    Worker_Role: "Assistant",
  },
  {
    id: "3",
    name: "Arience",
    profileImage: ProfileImages.Pic3,
    countryImage: FlagPics.Flag3,
    Worker_Role: "Makeup",
  },
  {
    id: "4",
    name: "Victoria",
    profileImage: ProfileImages.Pic4,
    countryImage: FlagPics.Flag4,
    Worker_Role: "Mehandi",
  },
  {
    id: "5",
    name: "Gladys",
    profileImage: ProfileImages.Pic13,
    countryImage: FlagPics.Flag5,
    Worker_Role: "Photographer",
  },
  {
    id: "6",
    name: "Darrell",
    profileImage: ProfileImages.Pic14,
    countryImage: FlagPics.Flag4,
    Worker_Role: "Assistant",
  },
  {
    id: "7",
    name: "Kyle",
    profileImage: ProfileImages.Pic5,
    countryImage: FlagPics.Flag1,
    Worker_Role: "Assistant",
  },
  {
    id: "8",
    name: "Marjorie",
    profileImage: ProfileImages.Pic15,
    countryImage: FlagPics.Flag3,
    Worker_Role: "Makeup",
  },
  {
    id: "9",
    name: "Kristin",
    profileImage: ProfileImages.Pic16,
    countryImage: FlagPics.Flag2,
    Worker_Role: "Assistant",
  },
  {
    id: "10",
    name: "Dianne",
    profileImage: ProfileImages.Pic6,
    countryImage: FlagPics.Flag3,
    Worker_Role: "Assistant",
  },
  {
    id: "11",
    name: "Philip",
    profileImage: ProfileImages.Pic7,
    countryImage: FlagPics.Flag5,
    Worker_Role: "Astrologer",
  },
  {
    id: "12",
    name: "Ronald",
    profileImage: ProfileImages.Pic8,
    countryImage: FlagPics.Flag1,
    Worker_Role: "Mehandi",
  },
  {
    id: "13",
    name: "Mitchell",
    profileImage: ProfileImages.Pic9,
    countryImage: FlagPics.Flag4,
    Worker_Role: "Photographer",
  },
  {
    id: "14",
    name: "Greg",
    profileImage: ProfileImages.Pic17,
    countryImage: FlagPics.Flag5,
    Worker_Role: "Makeup",
  },
  {
    id: "15",
    name: "Eduardo",
    profileImage: ProfileImages.Pic18,
    countryImage: FlagPics.Flag3,
    Worker_Role: "Mehandi",
  },
  {
    id: "16",
    name: "Cameron",
    profileImage: ProfileImages.Pic19,
    countryImage: FlagPics.Flag1,
    Worker_Role: "Mehandi",
  },
  {
    id: "17",
    name: "Shane",
    profileImage: ProfileImages.Pic10,
    countryImage: FlagPics.Flag2,
    Worker_Role: "Photographer",
  },
  {
    id: "18",
    name: "Arthur",
    profileImage: ProfileImages.Pic11,
    countryImage: FlagPics.Flag4,
    Worker_Role: "Photographer",
  },
  {
    id: "19",
    name: "Debra",
    profileImage: ProfileImages.Pic20,
    countryImage: FlagPics.Flag1,
    Worker_Role: "Astrologer",
  },
  {
    id: "20",
    name: "Darlene",
    profileImage: ProfileImages.Pic12,
    countryImage: FlagPics.Flag3,
    Worker_Role: "Photographer",
  },
];
